name: ebf_ai_presentation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  audioplayers: ^6.6.0
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  url_launcher: ^6.3.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/essex_rising.mp3
    - assets/lyrics.lrc

